apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
# username and password have already been base64-encrypted
    mongo-root-username: dXNlcm5hbWU=
    mongo-root-password: cGFzc3dvcmQ=
